version: '3.8'

services:
  dashboard-hub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: dashboard-hub-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      # Add your production environment variables here
      # - NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
      # - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY=your-anon-key
      # - SUPABASE_SERVICE_ROLE_KEY=your-service-role-key
      # - NEXT_PUBLIC_APP_URL=https://dashboard.your-domain.com
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dashboard-network:
    driver: bridge
